[package]
name = "rust-syn-flood"
version = "0.1.0"
authors = ["Mulyu <mulyu@hotmail.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.28.0"
rand = "0.8.4"